### PR TITLE
Update to EFI Boot Guard v0.8

### PR DESCRIPTION
**Pull request by hoinmic**

### CODE REVIEW

**Comment by jan-kiszka** [comment]
So I'm awaiting the official patch on the list?

If you are at it and likely have an appropriate test env: Can we also dump the yocto compat level?

**Comment by hoinmic** [comment]
I will test the patch today to make sure everything is working.

**Comment by hoinmic** [comment]
Did the tests with the Yocto LTS version, everything works fine. The branch is ready to merge from my point of view.

I do not understand the question regarding LAYERSERIES_COMPAT. Do you want to update to a newer version than dunfell?

**Comment by jan-kiszka** [comment]
If you have no test setup for a recent Yocto version, then we have to wait for someone else picking that up.

**Comment by jan-kiszka** [comment]
Applied, thanks.

**Comment by hoinmic** [comment]
Based on your previous comment, I think you have no idea about Yocto.

**Comment by jan-kiszka** [comment]
Yocto LTS is at 3.1 which this layer declares to be compatible with. But as its remaining lifetime is not much longer than latest non-LTS release, people may already want to use that or work towards next LTS. If you don't, we need to wait for other contributors to take that step.

**Pull request closed without merging**
